AWSTemplateFormatVersion: '2010-09-09'
Resources:
  readUserConf:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: exports.readUserConf = function(event, context) {  context.succeed('OK');};
      Description: readUserConf
      Handler: index.readUserConf
      Role: !GetAtt 'LambdaReadUserConfRole.Arn'
      Runtime: !Ref nodejsversion
      MemorySize: 128
      Timeout: 300
  LambdaReadUserConfRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - !Ref 'WriteGrants'
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ReadValidGroups
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: ReadValidGroupObjects
                Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::${AWS::StackName}-gator/conf/groups/*'
                  - !Sub 'arn:aws:s3:::${AWS::StackName}-gator/conf/grants/*'
              - Sid: ListValidGroupObjects
                Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${AWS::StackName}-gator'
                Condition:
                  ForAnyValue:StringEquals:
                    s3:prefix:
                      - conf/groups
                      - conf/grants
  ConfChangesTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Configuration Changes
      Subscription:
        - Endpoint: !GetAtt 'readUserConf.Arn'
          Protocol: lambda
  ConfChangesPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt 'readUserConf.Arn'
      Principal: sns.amazonaws.com
      SourceArn: !Ref 'ConfChangesTopic'
Outputs: {}
